#!/usr/bin/env bash
#Transfer file from this machine to a server

IFS='/'
if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	read -a path <<< "$1"
	scp -i $4 $3@localhost:$1 $2:"~/${path[-1]}"
fi
