#!/usr/bin/env bash
#install nginx and set it up

sudo apt-get -y install nginx && sudo ufw allow 'Nginx HTTP' &&\
sudo touch /var/www/html/index.html &&\
sudo chmod 0777 /var/www/html/index.html &&\
echo 'Hello World!'>/var/www/html/index.html
