#!/usr/bin/env bash
#redirects to www.google.com

sudo chmod a+wrx /etc/nginx/sites-available/ &&\

new="server_name _;\n\t location \/redirect_me {\n\treturn 301 https\:\/\/www.google.com;\n\t}"

sed -i "s/server_name _;/$new/" /etc/nginx/sites-available/default
sudo service nginx reload
