#!/usr/bin/env bash
#redirects to www.google.com

sudo apt-get -y update
sudo apt-get -y install nginx && sudo ufw allow 'Nginx HTTP'
sudo service nginx start

if [[ ! -d /var/www/html ]]
then
        sudo mkdir /var/www/html
fi
sudo chown -R "$USER":"$USER" /var/www/html
sudo touch /var/www/html/index.html &&\
sudo chmod 0777 /var/www/html/index.html &&\
echo 'Hello World!'>/var/www/html/index.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-available
sudo chmod a+wrx /etc/nginx/sites-available/ &&\
sudo chmod a+wrx /etc/nginx/sites-available/default
sudo chmod a+wrx /etc/nginx/sites-enabled/default
new="server_name _;\n\t location \/redirect_me {\n\treturn 301 https\:\/\/www.google.com;\n\t}"

sed -i "s/server_name _;/$new/" /etc/nginx/sites-available/default
sudo service nginx reload
