#!/usr/bin/env bash
#configure server with a new header

sudo apt-get -y update
sudo apt-get -y install nginx && sudo ufw allow 'Nginx HTTP'
sudo service nginx start

sudo chmod a+wrx /etc/nginx/sites-available/
name=$(sudo hostname)
new="add_header X-Served-By "$name";\n\t\ttry_files \$uri \$uri\/ =404;"

sed -i "s/try_files \$uri \$uri\/ =404;/$new/" /etc/nginx/sites-available/default

new2="#\t\tadd_header X-Served-By "$name";\n#\t\ttry_files \$uri \$uri\/ =404;"

sed -i "s/#\t\tadd_header X-Served-By "$name";/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
