#!/usr/bin/env bash
#make nginx listen on post 80

sudo chmod a+w /etc/nginx/sites-enabled/ &&\
sudo chmod a+w /etc/nginx/sites-enabled/default
sudo chmod a+w /etc/nginx/sites-available/

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default


sudo sed -i "s/ipv6only=on/""/" /etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=on/""/" /etc/nginx/sites-available/default
sudo service nginx restart
